name: Deploy FastAPI

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t pchelkovskiy/resortsweatherapi-api:${{ github.sha }} .
          docker push pchelkovskiy/resortsweatherapi-api:${{ github.sha }}
          docker tag pchelkovskiy/resortsweatherapi-api:${{ github.sha }} pchelkovskiy/resortsweatherapi-api:latest
          docker push pchelkovskiy/resortsweatherapi-api:latest

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        run: |
          az containerapp update \
            --name resort-weather-api \
            --resource-group portfolio-rg \
            --image docker.io/pchelkovskiy/resortsweatherapi-api:${{ github.sha }}